version: '3.9'
services:
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis123
    volumes: 
      - cache:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - '5540:5540'
volumes:
  cache:
    driver: local

