version: '3.9'
services:
  mariadb:
    image: bitnami/mariadb:11.4.6
    restart: always
    environment:
      - DB_SERVICE_NAME=dbcluster
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=metadata
      - MARIADB_USER=mydbuser
      - MARIADB_PASSWORD=mydbpass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data: